version: '3'

networks:
  default:
    internal: true
  public:
    external:
      name: net-pastis-hosting-docker_public

services:
  icecast:
    image: infiniteproject/icecast:latest
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.icecast-ruedesgardes-tcp.loadbalancer.server.port=8000"
      - "traefik.tcp.routers.icecast-ruedesgardes-tcp.service=icecast-ruedesgardes-tcp"
      - "traefik.tcp.routers.icecast-ruedesgardes-tcp.entrypoints=http"
      - "traefik.http.services.icecast-ruedesgardes.loadbalancer.server.port=8000"
      - "traefik.http.routers.icecast-ruedesgardes.service=icecast-ruedesgardes"
      - "traefik.http.routers.icecast-ruedesgardes.entrypoints=http"
      - "traefik.http.routers.icecast-ruedesgardes.rule=Host(`stream.ruedesgardes.org`)"
    env_file: .env
    networks:
      - default
      - public
